### ISSUE TITLE
composer installation / redundant composer structure

### ISSUE THREAD

**Issue by azngeek** [shopwareBoostDay/ask-me-anything#3]
It seems like that currently some plugins do have a subfolder for an own composer dependency management. This leads to several issues.

- You need to maintain separate dependencies in plugins. Instead there should be a general dependency in the root compose.json. However i do understand that if you develop a plugin that you do not want to break things but this is what composer is good for, right? 
- You need to implement your own autoloader or at least add another autoloader so that the required libraries will be loaded in the correct order
- Auto-completion in the IDE is not optimal as you will have redundant packages in maybe different versions.
- You can not trust a local composer.lock file as there might be several ones.

It think that it is important to understand design decisions in general so that you can deal with the current situation. However we have figured a way to install plugins using composer and would like to contribute it for the boosting-day. Let me know if this is a relevant issue for you. You also might take a look at how also Adobe/Magento implement it. This is the most convenient way for us https://devdocs.magento.com/cloud/howtos/install-components.html.

Zip-Files should not be the standard anymore :)

**Comment by mitelg** [comment]
hey @azngeek 
this will be possible with upcoming Shopware 6.4.0.0
You can already try it, and see if it fits your needs. Feedback is very welcome here :blush: :+1: 

https://github.com/shopware/platform/blob/trunk/src/Docs/Resources/current/60-references-internals/40-plugins/020-plugin-base-class.md#executecomposercommands

This happens here 
- https://github.com/shopware/platform/blob/trunk/src/Core/Framework/Plugin/PluginLifecycleService.php#L167
- https://github.com/shopware/platform/blob/trunk/src/Core/Framework/Plugin/Composer/CommandExecutor.php#L31

**Comment by ndzoesch** [comment]
Since this is a rather complex question and answer and Micheal already answered it, we won't answer it in the upcoming video. :)
